//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MembershipChargeId { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
    
        public virtual MembershipCharge MembershipCharge { get; set; }
        public virtual User User { get; set; }
    }
}
