//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sports2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSlotRequest
    {
        public int RequestId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> TimeSlotId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual TimeSlot TimeSlot { get; set; }
        public virtual User User { get; set; }
    }
}
